general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    color = rgba(0, 0, 0, 0.92)
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_family = JetBrainsMono Nerd Font Mono
    font_size = 18
    color = rgba(176, 176, 176, 0.7)
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_family = JetBrainsMono Nerd Font Mono
    font_size = 72
    color = rgba(208, 208, 208, 1.0)
    position = 0, -10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(176, 176, 176, 0.3)
    check_color = rgba(0, 0, 0, 1.0)
    fail_color = rgba(176, 0, 0, 0.6)
    font_color = rgba(208, 208, 208, 1.0)
    font_family = JetBrainsMono Nerd Font Mono
    placeholder_text = Password
    rounding = 6
    fade_on_empty = false
    position = 0, 80
    halign = center
    valign = center
}
