# autostart

exec-once = bash -c 'sleep 1 && $HOME/.config/hypr/scripts/first-boot.sh' # gtk + cursor, runs once
exec-once = swaybg -i ~/.config/images/wallpapers/4.jpg -m fill # wallpaper
exec-once = mkdir -p ~/Pictures/screenshots # screenshots dir
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # auth agent
exec-once = waybar &
exec-once = mako & # notifications
exec-once = wl-paste --watch cliphist store # clipboard history
